// Daftar platform untuk username scan (Sherlock-style, status-based).
// Untuk cakupan 300+ penuh, import data.json resmi Sherlock:
// https://github.com/sherlock-project/sherlock/blob/master/sherlock_project/resources/data.json
export type PlatformCategory =
  | "social"
  | "dev"
  | "gaming"
  | "forum"
  | "dating"
  | "ecommerce"
  | "media"
  | "blog"
  | "art"
  | "crypto"
  | "other";

export interface Platform {
  name: string;
  category: PlatformCategory;
  url: string; // {u} = username
}

export const PLATFORMS: Platform[] = [
  // social
  { name: "X / Twitter", category: "social", url: "https://x.com/{u}" },
  { name: "Instagram", category: "social", url: "https://www.instagram.com/{u}" },
  { name: "TikTok", category: "social", url: "https://www.tiktok.com/@{u}" },
  { name: "Facebook", category: "social", url: "https://www.facebook.com/{u}" },
  { name: "LinkedIn", category: "social", url: "https://www.linkedin.com/in/{u}" },
  { name: "Pinterest", category: "social", url: "https://www.pinterest.com/{u}" },
  { name: "Threads", category: "social", url: "https://www.threads.net/@{u}" },
  { name: "Bluesky", category: "social", url: "https://bsky.app/profile/{u}" },
  { name: "Mastodon", category: "social", url: "https://mastodon.social/@{u}" },
  { name: "Telegram", category: "social", url: "https://t.me/{u}" },
  { name: "VK", category: "social", url: "https://vk.com/{u}" },
  { name: "Tumblr", category: "social", url: "https://{u}.tumblr.com" },
  { name: "Reddit", category: "social", url: "https://www.reddit.com/user/{u}" },
  { name: "Quora", category: "social", url: "https://www.quora.com/profile/{u}" },
  { name: "Ask.fm", category: "social", url: "https://ask.fm/{u}" },
  { name: "Snapchat", category: "social", url: "https://www.snapchat.com/add/{u}" },
  { name: "Gravatar", category: "social", url: "https://gravatar.com/{u}" },
  { name: "About.me", category: "social", url: "https://about.me/{u}" },
  { name: "Linktree", category: "social", url: "https://linktr.ee/{u}" },
  { name: "Carrd", category: "social", url: "https://{u}.carrd.co" },
  { name: "Beacons", category: "social", url: "https://beacons.ai/{u}" },
  { name: "Warpcast", category: "social", url: "https://warpcast.com/{u}" },
  { name: "Minds", category: "social", url: "https://www.minds.com/{u}" },
  { name: "Gab", category: "social", url: "https://gab.com/{u}" },
  { name: "Gettr", category: "social", url: "https://gettr.com/user/{u}" },
  { name: "Truth Social", category: "social", url: "https://truthsocial.com/@{u}" },
  { name: "Vero", category: "social", url: "https://vero.co/{u}" },
  { name: "Ello", category: "social", url: "https://ello.co/{u}" },
  { name: "Clubhouse", category: "social", url: "https://www.clubhouse.com/@{u}" },
  { name: "Flipboard", category: "social", url: "https://flipboard.com/@{u}" },
  { name: "Foursquare", category: "social", url: "https://foursquare.com/{u}" },
  { name: "TripAdvisor", category: "social", url: "https://www.tripadvisor.com/Profile/{u}" },
  // dev
  { name: "GitHub", category: "dev", url: "https://github.com/{u}" },
  { name: "GitLab", category: "dev", url: "https://gitlab.com/{u}" },
  { name: "Bitbucket", category: "dev", url: "https://bitbucket.org/{u}" },
  { name: "Codeberg", category: "dev", url: "https://codeberg.org/{u}" },
  { name: "Gitee", category: "dev", url: "https://gitee.com/{u}" },
  { name: "SourceForge", category: "dev", url: "https://sourceforge.net/u/{u}" },
  { name: "Stack Overflow", category: "dev", url: "https://stackoverflow.com/users/{u}" },
  { name: "Dev.to", category: "dev", url: "https://dev.to/{u}" },
  { name: "Hashnode", category: "dev", url: "https://{u}.hashnode.dev" },
  { name: "Hacker Noon", category: "dev", url: "https://hackernoon.com/u/{u}" },
  { name: "Codepen", category: "dev", url: "https://codepen.io/{u}" },
  { name: "JSFiddle", category: "dev", url: "https://jsfiddle.net/user/{u}" },
  { name: "Replit", category: "dev", url: "https://replit.com/@{u}" },
  { name: "CodeSandbox", category: "dev", url: "https://codesandbox.io/u/{u}" },
  { name: "Kaggle", category: "dev", url: "https://www.kaggle.com/{u}" },
  { name: "Hugging Face", category: "dev", url: "https://huggingface.co/{u}" },
  { name: "npm", category: "dev", url: "https://www.npmjs.com/~{u}" },
  { name: "PyPI", category: "dev", url: "https://pypi.org/user/{u}" },
  { name: "Docker Hub", category: "dev", url: "https://hub.docker.com/u/{u}" },
  { name: "LeetCode", category: "dev", url: "https://leetcode.com/{u}" },
  { name: "HackerRank", category: "dev", url: "https://www.hackerrank.com/{u}" },
  { name: "Codeforces", category: "dev", url: "https://codeforces.com/profile/{u}" },
  { name: "Codewars", category: "dev", url: "https://www.codewars.com/users/{u}" },
  { name: "Exercism", category: "dev", url: "https://exercism.org/profiles/{u}" },
  { name: "freeCodeCamp", category: "dev", url: "https://www.freecodecamp.org/{u}" },
  { name: "Codecademy", category: "dev", url: "https://www.codecademy.com/profiles/{u}" },
  { name: "TryHackMe", category: "dev", url: "https://tryhackme.com/p/{u}" },
  { name: "HackerOne", category: "dev", url: "https://hackerone.com/{u}" },
  { name: "Bugcrowd", category: "dev", url: "https://bugcrowd.com/{u}" },
  { name: "Keybase", category: "dev", url: "https://keybase.io/{u}" },
  { name: "Observable", category: "dev", url: "https://observablehq.com/@{u}" },
  { name: "GeeksforGeeks", category: "dev", url: "https://www.geeksforgeeks.org/user/{u}" },
  { name: "Hacker News", category: "forum", url: "https://news.ycombinator.com/user?id={u}" },
  { name: "Lobsters", category: "forum", url: "https://lobste.rs/u/{u}" },
  { name: "Slashdot", category: "forum", url: "https://slashdot.org/~{u}" },
  // gaming
  { name: "Twitch", category: "gaming", url: "https://www.twitch.tv/{u}" },
  { name: "Kick", category: "gaming", url: "https://kick.com/{u}" },
  { name: "Steam", category: "gaming", url: "https://steamcommunity.com/id/{u}" },
  { name: "itch.io", category: "gaming", url: "https://{u}.itch.io" },
  { name: "Game Jolt", category: "gaming", url: "https://gamejolt.com/@{u}" },
  { name: "Newgrounds", category: "gaming", url: "https://{u}.newgrounds.com" },
  { name: "Chess.com", category: "gaming", url: "https://www.chess.com/member/{u}" },
  { name: "Lichess", category: "gaming", url: "https://lichess.org/@/{u}" },
  { name: "Speedrun.com", category: "gaming", url: "https://www.speedrun.com/users/{u}" },
  { name: "NameMC", category: "gaming", url: "https://namemc.com/profile/{u}" },
  { name: "PSN Profiles", category: "gaming", url: "https://psnprofiles.com/{u}" },
  { name: "TrueAchievements", category: "gaming", url: "https://www.trueachievements.com/gamer/{u}" },
  { name: "Exophase", category: "gaming", url: "https://www.exophase.com/user/{u}" },
  { name: "RetroAchievements", category: "gaming", url: "https://retroachievements.org/user/{u}" },
  { name: "Faceit", category: "gaming", url: "https://www.faceit.com/en/players/{u}" },
  { name: "Tracker.gg Valorant", category: "gaming", url: "https://tracker.gg/valorant/profile/riot/{u}" },
  // media
  { name: "YouTube", category: "media", url: "https://www.youtube.com/@{u}" },
  { name: "Vimeo", category: "media", url: "https://vimeo.com/{u}" },
  { name: "Dailymotion", category: "media", url: "https://www.dailymotion.com/{u}" },
  { name: "Rumble", category: "media", url: "https://rumble.com/c/{u}" },
  { name: "Odysee", category: "media", url: "https://odysee.com/@{u}" },
  { name: "Spotify", category: "media", url: "https://open.spotify.com/user/{u}" },
  { name: "SoundCloud", category: "media", url: "https://soundcloud.com/{u}" },
  { name: "Mixcloud", category: "media", url: "https://www.mixcloud.com/{u}" },
  { name: "Bandcamp", category: "media", url: "https://{u}.bandcamp.com" },
  { name: "Last.fm", category: "media", url: "https://www.last.fm/user/{u}" },
  { name: "Genius", category: "media", url: "https://genius.com/artists/{u}" },
  { name: "Imgur", category: "media", url: "https://imgur.com/user/{u}" },
  { name: "Giphy", category: "media", url: "https://giphy.com/{u}" },
  { name: "Tenor", category: "media", url: "https://tenor.com/users/{u}" },
  { name: "9GAG", category: "media", url: "https://9gag.com/u/{u}" },
  { name: "Flickr", category: "media", url: "https://www.flickr.com/people/{u}" },
  { name: "500px", category: "media", url: "https://500px.com/p/{u}" },
  { name: "VSCO", category: "media", url: "https://vsco.co/{u}" },
  { name: "Unsplash", category: "media", url: "https://unsplash.com/@{u}" },
  { name: "Pexels", category: "media", url: "https://www.pexels.com/@{u}" },
  { name: "Letterboxd", category: "media", url: "https://letterboxd.com/{u}" },
  { name: "Trakt", category: "media", url: "https://trakt.tv/users/{u}" },
  { name: "MyAnimeList", category: "media", url: "https://myanimelist.net/profile/{u}" },
  { name: "AniList", category: "media", url: "https://anilist.co/user/{u}" },
  { name: "Kitsu", category: "media", url: "https://kitsu.io/users/{u}" },
  { name: "Goodreads", category: "media", url: "https://www.goodreads.com/{u}" },
  { name: "Wattpad", category: "media", url: "https://www.wattpad.com/user/{u}" },
  { name: "Archive of Our Own", category: "media", url: "https://archiveofourown.org/users/{u}" },
  { name: "Untappd", category: "media", url: "https://untappd.com/user/{u}" },
  { name: "Strava", category: "media", url: "https://www.strava.com/athletes/{u}" },
  { name: "Duolingo", category: "media", url: "https://www.duolingo.com/profile/{u}" },
  // blog / writing
  { name: "Medium", category: "blog", url: "https://medium.com/@{u}" },
  { name: "Substack", category: "blog", url: "https://{u}.substack.com" },
  { name: "WordPress", category: "blog", url: "https://{u}.wordpress.com" },
  { name: "Blogger", category: "blog", url: "https://{u}.blogspot.com" },
  { name: "Ghost", category: "blog", url: "https://{u}.ghost.io" },
  { name: "SlideShare", category: "blog", url: "https://www.slideshare.net/{u}" },
  { name: "Scribd", category: "blog", url: "https://www.scribd.com/user/{u}" },
  { name: "Issuu", category: "blog", url: "https://issuu.com/{u}" },
  { name: "Product Hunt", category: "blog", url: "https://www.producthunt.com/@{u}" },
  { name: "Indie Hackers", category: "blog", url: "https://www.indiehackers.com/{u}" },
  // art
  { name: "Behance", category: "art", url: "https://www.behance.net/{u}" },
  { name: "Dribbble", category: "art", url: "https://dribbble.com/{u}" },
  { name: "Figma", category: "art", url: "https://www.figma.com/@{u}" },
  { name: "DeviantArt", category: "art", url: "https://www.deviantart.com/{u}" },
  { name: "ArtStation", category: "art", url: "https://www.artstation.com/{u}" },
  { name: "Pixiv", category: "art", url: "https://www.pixiv.net/en/users/{u}" },
  { name: "Instructables", category: "art", url: "https://www.instructables.com/member/{u}" },
  { name: "Hackaday.io", category: "art", url: "https://hackaday.io/{u}" },
  { name: "Thingiverse", category: "art", url: "https://www.thingiverse.com/{u}" },
  { name: "Printables", category: "art", url: "https://www.printables.com/@{u}" },
  // ecommerce
  { name: "Etsy", category: "ecommerce", url: "https://www.etsy.com/shop/{u}" },
  { name: "eBay", category: "ecommerce", url: "https://www.ebay.com/usr/{u}" },
  { name: "Fiverr", category: "ecommerce", url: "https://www.fiverr.com/{u}" },
  { name: "Upwork", category: "ecommerce", url: "https://www.upwork.com/freelancers/~{u}" },
  { name: "Freelancer", category: "ecommerce", url: "https://www.freelancer.com/u/{u}" },
  { name: "Patreon", category: "ecommerce", url: "https://www.patreon.com/{u}" },
  { name: "Ko-fi", category: "ecommerce", url: "https://ko-fi.com/{u}" },
  { name: "BuyMeACoffee", category: "ecommerce", url: "https://www.buymeacoffee.com/{u}" },
  // crypto
  { name: "OpenSea", category: "crypto", url: "https://opensea.io/{u}" },
  { name: "Rarible", category: "crypto", url: "https://rarible.com/user/{u}" },
  { name: "Mirror", category: "crypto", url: "https://mirror.xyz/{u}" },
  // other
  { name: "Wikipedia", category: "other", url: "https://en.wikipedia.org/wiki/User:{u}" },
  { name: "Wikimedia", category: "other", url: "https://meta.wikimedia.org/wiki/User:{u}" },
  { name: "Fandom", category: "other", url: "https://community.fandom.com/wiki/User:{u}" },
  { name: "OpenStreetMap", category: "other", url: "https://www.openstreetmap.org/user/{u}" },
  { name: "ResearchGate", category: "other", url: "https://www.researchgate.net/profile/{u}" },
  { name: "Academia.edu", category: "other", url: "https://independent.academia.edu/{u}" },
  { name: "ORCID", category: "other", url: "https://orcid.org/{u}" },
  { name: "Calendly", category: "other", url: "https://calendly.com/{u}" },
  { name: "Wellfound", category: "other", url: "https://wellfound.com/u/{u}" },
  { name: "Neopets", category: "other", url: "https://www.neopets.com/userlookup.phtml?user={u}" },
  { name: "Gaia Online", category: "other", url: "https://www.gaiaonline.com/profiles/{u}" },
  { name: "IMVU", category: "other", url: "https://www.imvu.com/next/av/{u}" },
  // dating (public profile only)
  { name: "Fetlife", category: "dating", url: "https://fetlife.com/{u}" },
  { name: "Couchsurfing", category: "dating", url: "https://www.couchsurfing.com/people/{u}" },
];
